mulai:
	gcc Spesifikasi/load.c Spesifikasi/start.c tambahan.c ADT/mesinkata.c ADT/mesinkarakter.c ADT/queue.c ADT/stack.c ADT/map.c ADT/list_dinamis.c ADT/listStatik.c ADT/set.c Spesifikasi/help.c Spesifikasi/quit.c ADT/list_linier.c Spesifikasi/list.c Spesifikasi/play.c Spesifikasi/status.c Spesifikasi/save.c Spesifikasi/queue.c Spesifikasi/song.c Tambahan/nyoba.c main.c -o main
